print("Hello world!")
print("Not another hello world")
print("No")
print("More")
print("Hello")
print("World")
print("Please, I'm begging you")
print("No")
print("Hello")
print("Please, I'm begging you")
